### ISSUE TITLE
Incorrect where generation after update to squel@4.4.1

### ISSUE THREAD

**Issue by Buinskii** [hiddentao/squel#221] opened 2016-03-22 17:06 UTC
I`m use node v0.10.38
This code:
```javascript
    var query = squel.select()
        .from('service.dateid')
        .field('id AS dateid')
        .where('date = \''+ date + '\'')
        .toString()
    ;
```
and this code:
```javascript
    var query = squel.select()
        .from(DateId.DATE_ID_TABLE)
        .field('id AS dateid')
        .where('date = ?', date)
        .toString()
    ;
```

generate incorrect next query:
```
SELECT id AS dateid FROM service.dateid WHERE (date = '2013-01-01'ddddddddddddddddddddddddddd)
```

**Comment by hiddentao** [comment] 2016-03-23 15:21
This seems to be similar to #220. I'm still investigating what the issue is. Am closing this as it's a duplicate of that one.

**Closed by hiddentao** 2016-03-23 15:21 UTC
Labels: Bug

**Comment by hiddentao** [comment] 2016-03-23 16:33
Please try 4.4.2 - this should be fixed now.

**Comment by Buinskii** [comment] 2016-03-23 17:35
It`s work for me, thank you!
