### ISSUE TITLE
node 0.10 support

### ISSUE THREAD

**Issue by kesla** [hiddentao/squel#219] opened 2016-03-19 19:01 UTC
We're seeing production issues updating to latest 4.4.0

```shell
ReferenceError: Symbol is not defined
    at _registerValueHandler (/var/local/cms/releases/cms-1458412259960-50d35e57-4ba2-45f9-a431-982b16f69036-60462d1/node_modules/@mic/squel/node_modules/squel/squel.js:175:38)
```

It seem, looking at `.travis.yml` it seem that you removed node 0.10 support - that's a breaking change.

**Comment by hiddentao** [comment] 2016-03-20 02:45
Sorry about that, I wasn't aware people were still using 0.10. Am fixing now.

**Comment by hiddentao** [comment] 2016-03-20 02:50
Fixed in 4.4.1

**Closed by hiddentao** 2016-03-20 02:50 UTC

**Comment by clayzermk1** [comment] 2016-04-22 21:04
@hiddentao it looks like there was a possible regression of this issue in 5.x.
```
ReferenceError: Symbol is not defined
    at _registerValueHandler (/Users/claywalker/Workspace/API/node_modules/squel/squel.js:148:36)
    at Object._buildSquel.cls.registerValueHandler (/Users/claywalker/Workspace/API/node_modules/squel/squel.js:294:5)
    at _buildSquel (/Users/claywalker/Workspace/API/node_modules/squel/squel.js:1222:7)
    at /Users/claywalker/Workspace/API/node_modules/squel/squel.js:2971:13
    at object (/Users/claywalker/Workspace/API/node_modules/squel/squel.js:5:22)
    at Object.<anonymous> (/Users/claywalker/Workspace/API/node_modules/squel/squel.js:9:2)
```

Environment:
node: 0.10.44
npm: 3.8.7
squel: 5.0.4

**Comment by hiddentao** [comment] 2016-04-24 13:51
@clayzermk1 squel 5+ is not supported on Node 0.10. I'll add a note to the README to that effect.
