### ISSUE TITLE
Postgresql having clause

### ISSUE THREAD

**Issue by banzai-samurai** [hiddentao/squel#152] opened 2015-05-21 14:59 UTC
Good day,

Is it possible to use "having" clause of Postgresql in squel? 
Something like 

`squel.select().from('table', 't').left_join('table1, 't1', 't1.id = t1.id').field('t.name').field('count(t1.*)')
group('t.name').having('count(t1.*) > ?', 15);`

Do you plan to provide this feature?

**Comment by hiddentao** [comment] 2015-05-23 15:17
Closing this as it's a duplicate of #86.

**Closed by hiddentao** 2015-05-23 15:17 UTC
