### ISSUE TITLE
Latest version failing with simple expr()

### ISSUE THREAD

**Issue by jdonnerstag** [hiddentao/squel#210] opened 2016-02-23 12:45 UTC
Hi,

we have some code that did work until recently, when we upgraded to node v5.7, cleaned all the caches, removed node_modules and installed all modules from scratch. The error message is

TypeError: Cannot read property 'nodes' of undefined
    at Expression.cls.Expression.Expression.or (C:\Users\donnerst\software\digital-order\fc-1\node_modules\squel\squel.js:465:24)

The (shortened) code is
`
var sql = squel.select()
var expr = squel.expr()
expr.or("state = ?", this.mssql.STATE.ACTIVE)
sql.where(expr)
`

Any idea what is wrong why squel's nodes object is no longer defined squel.js:465:24??

thanks 
Juergen

**Comment by SergeS** [comment] 2016-02-23 13:51
Hi can you attach little more of your code and also package.json . As I cannot reproduce this error with given code

**Comment by jdonnerstag** [comment] 2016-02-23 21:09
The problem is cause by the following source code in one of our modules
`if (!Array.prototype.last) {
	Array.prototype.last = function () {
  		return this[this.length - 1]
	}
}`

When commented, squel is working fine again

**Comment by hiddentao** [comment] 2016-02-23 22:13
That's quite weird since that function isn't getting used as far as I can tell. Plus `Array.last` doesn't exist in official JS specs yet.

**Comment by SergeS** [comment] 2016-02-23 22:33
Hi, again, please send your package.json and bigger piece of code. Now when I execute your code, it works just fine

**Comment by jdonnerstag** [comment] 2016-02-24 07:52
package.json (dependencies)

>  "dependencies": {
    "basic-auth": "^1.0.3",
    "body-parser": "*",
    "config": "*",
    "cookie": "^0.2.3",
    "decimal.js": "*",
    "express": "*",
    "express-session": "*",
    "hbs": "*",
    "js2xmlparser": "*",
    "jsonschema": "*",
    "line-reader": "*",
    "measured": "*",
    "moment": "^2.10.6",
    "morgan": "*",
    "multer": "*",
    "node-config": "*",
    "node-getopt": "*",
    "node-uuid": "*",
    "q": "~2",
    "q-io": "*",
    "request": "*",
    "sax": "*",
    "serve-index": "*",
    "soap": "*",
    "squel": "*",
    "tedious": "*",
    "tedious-connection-pool": "*",
    "tedious-promises": "*",
    "traverse": "*",
    "unirest": "*",
    "vargs": "*",
    "winston": "*",
    "xml2js": "*"
  },
  "devDependencies": {
    "jsdoc": "*",
    "mocha": "*",
    "chai": "*",
    "chai-things": "*",
    "chai-as-promised": "*",
    "jshint": "*",
    "jscs": "*",
    "loadtest": "*"
  }
<

Test
>
'use strict'

var util = require('util')
var Q = require('q')
var squel = require("squel").useFlavour('mssql')

var logger = require('../util/logger')
var config = require('../util/fc-configs')
var MSSQL = require('../util/fc-mssql')

/*
if (!Array.prototype.last) {
	Array.prototype.last = function () {
  		return this[this.length - 1]
	}
}
*/

var sql = squel.select()
var expr = squel.expr()
expr.or("state = ?", this.mssql.STATE.ACTIVE)
sql.where(expr)
<

**Comment by SergeS** [comment] 2016-02-24 09:30
Found issue, fixed in PR #211

**Comment by hiddentao** [comment] 2016-02-24 09:59
Fixed in 4.3.2

**Closed** 2016-02-24 10:17 UTC
